# Use Node.js image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy rest of app
COPY . .

# Expose port
EXPOSE 5060

# Run the app
CMD ["node", "app.js"]
